[package]
authors = ["Jan Hohenheim <jan@hohenheim.ch>"]
edition = "2021"
name = "bevy_game"
publish = false
version = "0.1.0"

[features]
default = [   
    "bevy/bevy_winit",
    "bevy/render",
    "bevy/png",
    "bevy/x11",
    "bevy_kira_audio/ogg",
]

editor = [
    "dep:bevy_editor_pls",
]

dynamic = [
    "bevy/dynamic",
]

[dependencies]
bevy = { version = "0.9.1", default-features = false }
rand = "0.8.3"
bevy_kira_audio = "0.13.0"
bevy_asset_loader = "0.14.1"
bevy_editor_pls = { git = "https://github.com/jakobhellermann/bevy_editor_pls", optional = true }
bytemuck = { version = "1.9.1", features= [ "derive" ] }
bitflags = "1.3.2"

[target."cfg(target_os = \"linux\")".dependencies]
winit = { version = "0.25", features = [ "x11" ]}

[target."cfg(not(target_arch = \"wasm32\"))".dependencies]
clap = { version = "3.1.18", features = ["derive"] }

[build-dependencies]
embed-resource = "1.4"

